version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - area/dependencies
      - dependency/go

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - area/dependencies
      - dependency/github_actions
      - release-note/ignore

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - area/dependencies
      - dependency/docker
      - release-note/ignore

  - package-ecosystem: npm
    open-pull-requests-limit: 0
    directory: "/api/client/web"
    schedule:
      interval: weekly
    labels:
      - area/dependencies
      - dependency/javascript
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "eslint-formatter-pretty"

  - package-ecosystem: npm
    open-pull-requests-limit: 0
    directory: "/api/client/node"
    schedule:
      interval: weekly
    labels:
      - area/dependencies
      - dependency/javascript
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "eslint"
      - dependency-name: "eslint-formatter-pretty"

  - package-ecosystem: pip
    open-pull-requests-limit: 1
    directory: "/api/client/python"
    schedule:
      interval: weekly
    labels:
      - area/dependencies
      - dependency/python
      - release-note/dependency-update
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
