address: 127.0.0.1:8888

telemetry:
  log:
    level: debug

sink:
  kafkaConnect:
    enabled: true
    url: http://kafka-connect:8083
    connectors:
      - name: clickhouse
        type: clickhouse
        config:
          hostname: clickhouse
          port: 8123
          ssl: false
          database: openmeter
          username: default
          password: default
          deadLetterQueue:
            topicName: om_deadletterqueue
            replicationFactor: 1
            contextHeaders: true

# dedupe:
#   enabled: true
#   driver: redis
#   config:
#     address: 127.0.0.1:6379
#     database: 0
#     expiration: 768h # 32d

meters:
  - slug: m1
    eventType: api-calls
    valueProperty: $.duration_ms
    aggregation: SUM
    groupBy:
      method: $.method
      path: $.path
