apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benthos-collector.fullname" . }}
  labels:
    {{- include "benthos-collector.labels" . | nindent 4 }}
type: Opaque
data:
  OPENMETER_URL: {{ required "OpenMeter URL is required" .Values.openmeter.url | b64enc | quote }}
  {{- with .Values.openmeter.token }}
  OPENMETER_TOKEN: {{ . | b64enc | quote }}
  {{- end }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "benthos-collector.componentName" (list . "config") }}
  labels:
    {{- include "benthos-collector.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ .Values.config | toYaml | b64enc | quote }}
