ingest:
  kafka:
    broker: kafka:29092

aggregation:
  clickhouse:
    address: clickhouse:9000

sink:
  kafkaConnect:
    enabled: true
    url: http://kafka-connect:8083
    connectors:
      - name: clickhouse
        type: clickhouse
        config:
          hostname: clickhouse
          port: 8123
          ssl: false
          database: openmeter
          username: default
          password: default
          deadLetterQueue:
            topicName: om_deadletterqueue
            replicationFactor: 1
            contextHeaders: true

meters:
  - slug: m1
    description: API calls
    eventType: api-calls
    valueProperty: $.duration_ms
    aggregation: SUM
    groupBy:
      method: $.method
      path: $.path
  - slug: m2
    description: Open AI Tokens
    eventType: openai
    valueProperty: $.total_tokens
    aggregation: SUM
    groupBy:
      model: $.model
