version: '3.9'

services:
  openmeter:
    image: ghcr.io/openmeterio/openmeter
    command: openmeter --config /etc/openmeter/config.yaml
    hostname: openmeter
    container_name: openmeter
    restart: always
    pull_policy: always
    depends_on:
      storage-healthcheck:
        condition: service_healthy
    ports:
      - "8888:8888"
    volumes:
      - ./config.yaml:/etc/openmeter/config.yaml

  storage-healthcheck:
    image: curlimages/curl:8.2.1
    entrypoint: /bin/sh
    tty: true
    healthcheck:
      test: curl --fail --connect-timeout 5 http://ksqldb-server:8088/healthcheck || curl --fail --connect-timeout 5 http://clickhouse:8123/ping
      interval: 5s
      timeout: 5s
      retries: 100

  zookeeper:
    extends:
      file: ../docker-compose.yaml
      service: zookeeper

  broker:
    depends_on:
      - zookeeper
    extends:
      file: ../docker-compose.yaml
      service: broker
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://broker:29092

  schema:
    depends_on:
      - broker
    extends:
      file: ../docker-compose.yaml
      service: schema

  kafka-connect-01:
    depends_on:
      - broker
    extends:
      file: ../docker-compose.yaml
      service: kafka-connect-01

  # Profile: ksqldb
  ksqldb-server:
    depends_on:
      - broker
    extends:
      file: ../docker-compose.yaml
      service: ksqldb-server

  # Profile: clickhouse
  clickhouse:
    extends:
      file: ../docker-compose.yaml
      service: clickhouse

  # Profile: dedupe-redis
  redis:
    extends:
      file: ../docker-compose.yaml
      service: redis
