version: "3.9"

services:
  openmeter:
    image: ghcr.io/openmeterio/openmeter:latest
    command: openmeter --config /etc/openmeter/config.yaml
    restart: always
    pull_policy: always
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      ksqldb-server:
        condition: service_healthy
        required: false
      clickhouse:
        condition: service_healthy
        required: false
      kafka-connect:
        condition: service_healthy
        required: false
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - ./config.yaml:/etc/openmeter/config.yaml

  zookeeper:
    extends:
      file: ../docker-compose.yaml
      service: zookeeper

  kafka:
    extends:
      file: ../docker-compose.yaml
      service: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092
    healthcheck:
      test: kafka-topics --bootstrap-server kafka:9092 --list
      interval: 5s
      timeout: 3s
      retries: 100

  schema-registry:
    extends:
      file: ../docker-compose.yaml
      service: schema-registry
    healthcheck:
      test: curl --fail http://schema-registry:8081/subjects
      interval: 5s
      timeout: 3s
      retries: 100


  # Profile: ksqldb
  ksqldb-server:
    extends:
      file: ../docker-compose.yaml
      service: ksqldb-server
    healthcheck:
      test: curl --fail http://ksqldb-server:8088/healthcheck
      interval: 5s
      timeout: 3s
      retries: 100

  # Profile: clickhouse
  clickhouse:
    extends:
      file: ../docker-compose.yaml
      service: clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://clickhouse:8123/ping || exit 1
      interval: 5s
      timeout: 3s
      retries: 100

  kafka-connect:
    extends:
      file: ../docker-compose.yaml
      service: kafka-connect

  # Profile: dedupe-redis
  redis:
    extends:
      file: ../docker-compose.yaml
      service: redis
