version: '3.9'

services:
  openmeter:
    image: ghcr.io/openmeterio/openmeter
    command: openmeter --config /etc/openmeter/config.yaml
    hostname: openmeter
    container_name: openmeter
    restart: always
    pull_policy: always
    depends_on:
      ksqldb-healthcheck:
        condition: service_healthy
        required: false
      clickhouse:
        condition: service_healthy
        required: false
    ports:
      - "8888:8888"
    volumes:
      - ./config.yaml:/etc/openmeter/config.yaml


  zookeeper:
    extends:
      file: ../docker-compose.yaml
      service: zookeeper

  broker:
    depends_on:
      - zookeeper
    extends:
      file: ../docker-compose.yaml
      service: broker
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://broker:29092

  schema:
    depends_on:
      - broker
    extends:
      file: ../docker-compose.yaml
      service: schema

  kafka-connect-01:
    depends_on:
      - broker
    extends:
      file: ../docker-compose.yaml
      service: kafka-connect-01

  # Profile: ksqldb
  ksqldb-server:
    depends_on:
      - broker
    extends:
      file: ../docker-compose.yaml
      service: ksqldb-server

  ksqldb-healthcheck:
    profiles:
      - ksqldb
    depends_on:
      - ksqldb-server
    image: curlimages/curl:8.2.1
    entrypoint: /bin/sh
    tty: true
    healthcheck:
      test: curl --fail http://ksqldb-server:8088/healthcheck
      interval: 5s
      timeout: 3s
      retries: 100

  # Profile: clickhouse
  clickhouse:
    extends:
      file: ../docker-compose.yaml
      service: clickhouse
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 3s
      retries: 100

  # Profile: dedupe-redis
  redis:
    extends:
      file: ../docker-compose.yaml
      service: redis
