apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openmeter.fullname" . }}
  labels:
    {{- include "openmeter.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := .Values.config -}}
    {{- if .Values.kafka.enabled -}}
    {{- $config := omit $config "ingest" }}

    ingest:
      kafka:
        broker: PLAINTEXT://{{ include "openmeter.fullname" . }}-kafka-bootstrap:9092
    {{- end }}

    {{- if .Values.clickhouse.enabled -}}
    {{- $config := omit $config "aggregation" }}

    aggregation:
      clickhouse:
        address: clickhouse-{{ include "openmeter.fullname" . }}:9000
        username: default
        password: ""
        database: default
    {{- end }}


    {{- if .Values.config -}}
    {{ .Values.config | toYaml | nindent 4 }}
    {{- end }}
