name: Python Client Generation

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/openapi.yaml
      - ".github/workflows/generate-client-python.yaml"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Generate Client
        run: |
          make generate
        working-directory: ./api/client/python
      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: openapi/python-client
          branch-suffix: short-commit-hash
          delete-branch: true
          commit-message: "chore(api): generate python client"
          title: "[bot] Re-generate Python client"
          body: "This PR was automatically generated."
          labels: |
            area/api
            release-note/misc
          token: ${{ steps.app-token.outputs.token }}
