name: Publish Web client

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: "./api/client/web/pnpm-lock.yaml"
          registry-url: "https://registry.npmjs.org"
          scope: "@openmeter"
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./api/client/web
      - name: Bump version
        run: pnpm version ${{ github.ref_name }} --no-git-tag-version
        working-directory: ./api/client/web
      - name: Publish
        run: pnpm publish --access=public --no-git-checks
        working-directory: ./api/client/web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
